In [20]:
import pandas as pd
s = pd.Series([89.2, 76.4, 98.2, 75.9], index=list('abcd'))

In [21]:
if ('b' in s):
    print('Hi')

Hi


In [22]:
import pandas as pd

heights_A = pd.Series([8176.2, 158.4, 167.6, 156.2,161.4], index=['s1','s2','s3','s4','s5'])
weights_A = pd.Series([85.1, 90.2, 76.8, 80.4,78.9], index=['s1','s2','s3','s4','s5'])

# print(heights_A[1])
data = {"Student_height": heights_A, 
        "Student_weight": weights_A} 
df_A = pd.DataFrame(data)

df_s1s2 = df_A.loc[['s1','s2']]

print(df_s1s2)

    Student_height  Student_weight
s1          8176.2            85.1
s2           158.4            90.2


In [23]:
import pandas as pd

heights_A = pd.Series([8176.2, 158.4, 167.6, 156.2,161.4], index=['s1','s2','s3','s4','s5'])
weights_A = pd.Series([85.1, 90.2, 76.8, 80.4,78.9], index=['s1','s2','s3','s4','s5'])

# print(heights_A[1])
data = {"Student_height": heights_A, 
        "Student_weight": weights_A} 
df_A = pd.DataFrame(data)

df_s2s5s1 = df_A.loc[['s2','s5','s1']]

print(df_s2s5s1)

    Student_height  Student_weight
s2           158.4            90.2
s5           161.4            78.9
s1          8176.2            85.1


In [24]:
import pandas as pd

heights_A = pd.Series([8176.2, 158.4, 167.6, 156.2,161.4], index=['s1','s2','s3','s4','s5'])
weights_A = pd.Series([85.1, 90.2, 76.8, 80.4,78.9], index=['s1','s2','s3','s4','s5'])

# print(heights_A[1])
data = {"Student_height": heights_A, 
        "Student_weight": weights_A}
df_A = pd.DataFrame(data)

df_s1s4= df_A.loc[(df_A.index.str.endswith('1') | df_A.index.str.endswith('4'))]

print(df_s1s4)

    Student_height  Student_weight
s1          8176.2            85.1
s4           156.2            80.4


In [ ]:
df = pd.DataFrame({'A':[34, 78, 54], 'B':[12, 67, 43]}, index=['r1', 'r2', 'r3'])
df.loc['r4'] = [67, 78]


In [ ]:
df

In [ ]:
import pandas as pd

df = pd.DataFrame({'A':[34, 78, 54], 'B':[12, 67, 43]}, index=['r1', 'r2', 'r3'])

In [ ]:
df[:2]

In [ ]:
df.iloc[:2]

In [25]:
name = "M234onica"
print(name.isalnum())

# contains whitespace
name = "M3onica_Gell22er "
print(name.isalnum())

name = "Mo3nicaGell22er"
print(name.isalnum())

name = "133"
print(name.isalnum())

True
False
True
True


In [26]:
s = "282.12"
print(s.isdecimal())

# contains alphabets
s = "32ladk3"
print(s.isdecimal())

# contains alphabets and spaces
s = "Mo3 nicaG el l22er"
print(s.isdecimal())

False
False
False


In [27]:
l = ["ronit","raj","sahu"]
l.sort(key = len, reverse = True)
l

['ronit', 'sahu', 'raj']

In [28]:
del l[1]

In [29]:
l

['ronit', 'raj']

In [30]:
del l

In [31]:
l

NameError: name 'l' is not defined

In [32]:
d = {1: "one", 2: "two"}

d.clear()
print('d =', d)

d = {}


In [33]:
d

{}

In [34]:
# vowels keys
# keys = {'a', 'e', 'i', 'o', 'u' }
keys = ['a', 'e', 'i', 'o', 'u' ]

vowels = dict.fromkeys(keys)
print(vowels)

{'a': None, 'e': None, 'i': None, 'o': None, 'u': None}


In [36]:
for i in vowels.keys():
    vowels[i] = i
print(vowels)

{'a': 'a', 'e': 'e', 'i': 'i', 'o': 'o', 'u': 'u'}


In [35]:
# vowels keys
# keys = {'a', 'e', 'i', 'o', 'u' }
keys = ['a', 'e', 'i', 'o', 'u' ]
value = 'vowel'
vowels = dict.fromkeys(keys,value)
print(vowels)

{'a': 'vowel', 'e': 'vowel', 'i': 'vowel', 'o': 'vowel', 'u': 'vowel'}


In [38]:
person = {'name': 'Phill', 'age': 22}

print('Name: ', person.get('name'))
print('Age: ', person.get('age'))

# value is not provided
print('Salary: ', person.get('salary'))

# value is provided
print('Salary: ', person.get('salary', 0.0))
person

Name:  Phill
Age:  22
Salary:  None
Salary:  0.0


{'name': 'Phill', 'age': 22}

In [39]:
person = {}

# Using get() results in None
print('Salary: ', person.get('salary'))

# Using [] results in KeyError
print(person['salary'])

Salary:  None


KeyError: 'salary'

In [40]:
# random sales dictionary
sales = { 'apple': 2, 'orange': 3, 'grapes': 4 }

print(sales.items())

dict_items([('apple', 2), ('orange', 3), ('grapes', 4)])


In [ ]:
print([sales.items()])

In [ ]:
# random sales dictionary
sales = { 'apple': 2, 'orange': 3, 'grapes': 4 }

items = sales.items()
print('Original items:', items)

# delete an item from dictionary
del[sales['apple']]


print('Updated items:', items)

In [ ]:
person = {'name': 'Phill', 'age': 22, 'salary': 3500.0}

print(person.keys())

empty_dict = {}
print(empty_dict.keys())

In [46]:
person = {'name': 'Phill', 'age': 22, }

print('Before dictionary is updated')
keys = person.keys()
print(keys)

# adding an element to the dictionary
person.update({'salary': 3600.0})
print('\nAfter dictionary is updated')
print(keys)

person.update({'salary': 3500.0})

print(keys)
person

Before dictionary is updated
dict_keys(['name', 'age'])

After dictionary is updated
dict_keys(['name', 'age', 'salary'])
dict_keys(['name', 'age', 'salary'])


{'name': 'Phill', 'age': 22, 'salary': 3500.0}

In [50]:
person = {'name': 'Phill', 'age': 22, 'salary': 3500.0}

# ('salary', 3500.0) is inserted at the last, so it is removed.
result = person.pop('age')

print('Return Value = ', result)
print('person = ', person)

# inserting a new element pair

person['profession'] = 'Plumber'

# now ('profession', 'Plumber') is the latest element
result = person.popitem()

print('Return Value = ', result)
print('person = ', person)

Return Value =  22
person =  {'name': 'Phill', 'salary': 3500.0}
Return Value =  ('profession', 'Plumber')
person =  {'name': 'Phill', 'salary': 3500.0}


In [1]:
person = {'name': 'Phill'}

# key is not in the dictionary
salary = person.setdefault('salary')
print('person = ',person)
print('salary = ',salary)

# key is not in the dictionary
# default_value is provided
age = person.setdefault('age', 22)
print('person = ',person)
print('age = ',age)

person =  {'name': 'Phill', 'salary': None}
salary =  None
person =  {'name': 'Phill', 'salary': None, 'age': 22}
age =  22


In [57]:
# random sales dictionary
sales = { 'apple': 2, 'orange': 3, 'grapes': 4 }

element = sales.pop('guava', 'banana')
print('The popped element is:', element)
print('The dictionary is:', sales)

The popped element is: banana
The dictionary is: {'apple': 2, 'orange': 3, 'grapes': 4}


In [58]:
# random sales dictionary
sales = { 'apple': 2, 'orange': 3, 'grapes': 4 }

element = sales.pop('apple')
print('The popped element is:', element)
print('The dictionary is:', sales)

The popped element is: 2
The dictionary is: {'orange': 3, 'grapes': 4}


In [ ]:
# random sales dictionary
sales = { 'apple': 2, 'orange': 3, 'grapes': 4 }

print(sales.values())

In [ ]:
for i in sales.values():
    print(i)

In [ ]:
[i for i in sales.values()]

In [ ]:
d = {1: "one", 2: "three"}
d1 = {2: "two"}

# updates the value of key 2
d.update(d1)
print(d)

d1 = {3: "three"}

# adds element with key 3
d.update(d1)
print(d)

In [59]:
d = {'x': 2}

d.update(y = 3, z = 0)
print(d)

{'x': 2, 'y': 3, 'z': 0}


In [60]:
# empty set
print(set())

# from string
print(set('Python'))

# from tuple
print(set(('a', 'e', 'i', 'o', 'u')))

# from list
print(set(['a', 'e', 'i', 'o', 'u']))

# from range
print(set(range(5)))

set()
{'P', 'n', 'y', 'o', 'h', 't'}
{'i', 'e', 'o', 'u', 'a'}
{'i', 'e', 'o', 'u', 'a'}
{0, 1, 2, 3, 4}


In [62]:
# from set
print(set({'a', 'e', 'i', 'o', 'u'}))

# from dictionary
print(set({'a':1, 'e': 2, 'i':3, 'o':4, 'u':5}))

# from frozen set
frozen_set = frozenset(('a', 'e', 'i', 'o', 'u'))
print(set(frozen_set))

{'o', 'i', 'e', 'u', 'a'}
{'o', 'e', 'i', 'u', 'a'}
{'o', 'i', 'e', 'u', 'a'}


In [63]:
fruits = {"apple", "banana", "cherry"}

fruits.add("orange")

print(fruits)

{'banana', 'orange', 'apple', 'cherry'}


In [64]:
x = {"apple", "banana", "cherry"}
y = {"google", "microsoft", "apple"}

z = x.difference(y)

print(z)

{'banana', 'cherry'}


In [65]:
x = {"apple", "banana", "cherry"}
y = {"google", "microsoft", "apple"}

x.difference_update(y)

print(x)

{'banana', 'cherry'}


In [66]:
x = {"apple", "banana", "cherry"}
y = {"google", "microsoft", "apple"}

z = x.intersection(y)

print(z)

{'apple'}


In [67]:
x = {"apple", "banana", "cherry"}
y = {"google", "microsoft", "apple"}

x.intersection_update(y)

print(x)

{'apple'}


In [68]:
x = {"apple", "banana", "cherry"}
y = {"google", "microsoft", "facebook"}

z = x.isdisjoint(y) 
z

True

In [69]:
x = {"apple", "banana", "cherry"}
y = {"google", "apple", "facebook"}

z = x.isdisjoint(y) 
z

False

In [70]:
x = {"apple", "banana", "cherry"}
y = {"google", "microsoft", "apple"}

z = x.symmetric_difference(y)

print(z)

{'banana', 'google', 'cherry', 'microsoft'}


In [71]:
x | y

{'apple', 'banana', 'cherry', 'google', 'microsoft'}

In [72]:
x & y

{'apple'}

In [73]:
x - y

{'banana', 'cherry'}

In [74]:
y - x

{'google', 'microsoft'}

In [76]:
import random

random.randrange(1, 10)

1

In [78]:
print(random.randint(1, 10))

6


In [79]:
s = "Ronitraj Sahu"

In [80]:
s[5:]

'raj Sahu'

In [81]:
s[:5]

'Ronit'

In [82]:
s[-5:]

' Sahu'

In [83]:
s[:-5]

'Ronitraj'

In [97]:
s[-6::-1]

'jartinoR'

In [98]:
def PowTwoGen(max=0):
    n = 0
    while n < max:
        yield 2 ** n
        n += 1
        
next(PowTwoGen(6))

1

In [99]:
n = PowTwoGen(6)

In [101]:
next(n)

2

In [105]:

result = list()
for i in range(int(input("Pleasen enter the number:"))):
    if i == 0:
        result.append(0)
    elif i == 1:
        result.append(1)
    else:
        result.append(result[i-2]+result[i-1])
    
for i in result:
    print(i,end = " ")

Pleasen enter the number:16
0 1 1 2 3 5 8 13 21 34 55 89 144 233 377 610 

In [107]:

result = list()
for i in range(5):
    if i == 0:
        result.append(0)
    elif i == 1:
        result.append(1)
    else:
        result.append(result[i-2]+result[i-1])
    
for i in result:
    print(i,end = " ")

0 1 1 2 3 

In [109]:
from math import sqrt
a = int(input("enter num ::")) 

if(sqrt(a) == a ** 0.5 ):
    print("Perfect Square")
else:
    print("Not perfect Square")

enter num ::5
Perfect Square


In [112]:
from math import sqrt
a = int(input("enter num ::")) 
a2 = sqrt(a)
if(a2 == int(a2) ):
    print("Perfect Square")
else:
    print("Not perfect Square")

enter num ::16
Perfect Square


In [113]:
sqrt(a)

4.0

In [114]:
sqrt(8)%1

0.8284271247461903

In [6]:
import numpy as np

a = np.array([[3,4],[7,2],[5,9]])
b = np.array([[3,1,5],[6,9,7]])


result = np.zeros((3,3))
for i in range(len(a)):
    for j in range(len(b[0])):
        for k in range(len(b)):
            result[i][j] += a[i][k]*b[k][j]
            
result

array([[33., 39., 43.],
       [33., 25., 49.],
       [69., 86., 88.]])

In [116]:
import numpy as np

A = np.zeros((2,3))
B = np.zeros((3,2))

for i in range(A.shape[0]):
    for j in range(A.shape[1]):
        A[i,j] = int(input())

for i in range(B.shape[0]):
    for j in range(B.shape[1]):
        B[i,j] = int(input())
        

result = np.zeros((A.shape[0],B.shape[1]))

for i in range(A.shape[0]):
    for j in range(B.shape[1]):
        for k in range(B.shape[0]):
            result[i][j] += A[i][k]*B[k][j]
            
result,A,B

12
36
16
14
13
17
19
13
16
15
23
3


(array([[1172.,  744.],
        [ 865.,  428.]]),
 array([[12., 36., 16.],
        [14., 13., 17.]]),
 array([[19., 13.],
        [16., 15.],
        [23.,  3.]]))

In [117]:
np.ones((5,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [8]:
np.full((2,3),'ronit')

array([['ronit', 'ronit', 'ronit'],
       ['ronit', 'ronit', 'ronit']], dtype='<U5')

In [118]:
np.random.rand(4,3)

array([[0.65167008, 0.39987239, 0.76352459],
       [0.68181681, 0.19001222, 0.84774836],
       [0.81404519, 0.92064247, 0.06993843],
       [0.0348025 , 0.23798118, 0.0866356 ]])

In [10]:
np.random.randint(4999,5001,size = (3,3))

array([[4999, 5000, 4999],
       [4999, 4999, 5000],
       [5000, 4999, 5000]])

In [12]:
np.random.randint(100,size = (3,3))

array([[17, 38, 96],
       [ 6, 11, 65],
       [18, 67, 35]])

In [13]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [14]:
c = np.identity(3)

In [15]:
np.matmul(a,b)

array([[33, 39, 43],
       [33, 25, 49],
       [69, 86, 88]])

In [16]:
np.linalg.det(c)

1.0

In [17]:
a

array([[3, 4],
       [7, 2],
       [5, 9]])

In [18]:
a.shape

(3, 2)

In [19]:
ashape = a.shape

In [20]:
ashape[1]

2

### Leap Year Problem

In [21]:
def checkleapyear(year):
    if year%400 == 0:
        return True
    elif year%100 == 0:
        return False
    elif year%4 == 0:
        return True
    else:
        return False
    
print(checkleapyear(2015))
print(checkleapyear(2000))
print(checkleapyear(2018))
print(checkleapyear(2008))
print(checkleapyear(1900))

False
True
False
True
False


In [22]:
from itertools import product  
    
print("The cartesian product using repeat:")  
print(list(product([1, 2], repeat = 2)))  
print(list(product([1, 2],[3,4])))  
print()  
    
print("The cartesian product of the containers:")  
print(list(product(['geeks', 'for', 'geeks'], '2')))  
print()  
    
print("The cartesian product of the containers:")  
print(list(product('AB', [3, 4]))) 

The cartesian product using repeat:
[(1, 1), (1, 2), (2, 1), (2, 2)]
[(1, 3), (1, 4), (2, 3), (2, 4)]

The cartesian product of the containers:
[('geeks', '2'), ('for', '2'), ('geeks', '2')]

The cartesian product of the containers:
[('A', 3), ('A', 4), ('B', 3), ('B', 4)]


In [122]:
# import the product function from itertools module 
from itertools import permutations 

print ("All the permutations of the given list is:") 
print (list(permutations([1, 'geeks']))) 
print() 
# Terminating iterators 
print ("All the permutations of the given string is:") 
peronit = list(''.join(x) for x in permutations('ronit',5))
print (peronit) 
print(len(peronit)) 

print ("All the permutations of the given container is:") 
print(list(permutations(range(3), 2))) 


All the permutations of the given list is:
[(1, 'geeks'), ('geeks', 1)]

All the permutations of the given string is:
['ronit', 'ronti', 'roint', 'roitn', 'rotni', 'rotin', 'rnoit', 'rnoti', 'rniot', 'rnito', 'rntoi', 'rntio', 'riont', 'riotn', 'rinot', 'rinto', 'riton', 'ritno', 'rtoni', 'rtoin', 'rtnoi', 'rtnio', 'rtion', 'rtino', 'ornit', 'ornti', 'orint', 'oritn', 'ortni', 'ortin', 'onrit', 'onrti', 'onirt', 'onitr', 'ontri', 'ontir', 'oirnt', 'oirtn', 'oinrt', 'ointr', 'oitrn', 'oitnr', 'otrni', 'otrin', 'otnri', 'otnir', 'otirn', 'otinr', 'nroit', 'nroti', 'nriot', 'nrito', 'nrtoi', 'nrtio', 'norit', 'norti', 'noirt', 'noitr', 'notri', 'notir', 'nirot', 'nirto', 'niort', 'niotr', 'nitro', 'nitor', 'ntroi', 'ntrio', 'ntori', 'ntoir', 'ntiro', 'ntior', 'iront', 'irotn', 'irnot', 'irnto', 'irton', 'irtno', 'iornt', 'iortn', 'ionrt', 'iontr', 'iotrn', 'iotnr', 'inrot', 'inrto', 'inort', 'inotr', 'intro', 'intor', 'itron', 'itrno', 'itorn', 'itonr', 'itnro', 'itnor', 'troni', 'troin',

In [ ]:
# import combinations from itertools module  
    
from itertools import combinations  
    
print ("All the combination of list in sorted order(without replacement) is:")   
print(list(combinations(['A', 2], 2)))  
print()  
    
print ("All the combination of string in sorted order(without replacement) is:")  
print(list(combinations('ABB', 2)))  
print()  
    
print ("All the combination of list in sorted order(without replacement) is:")  
print(list(combinations(range(3), 2)))  

In [ ]:
# import combinations from itertools module  
    
from itertools import combinations_with_replacement  
    
print ("All the combination of string in sorted order(with replacement) is:")  
print(list(combinations_with_replacement("AB", 5)))  
print()  
    
print ("All the combination of list in sorted order(with replacement) is:")  
print(list(combinations_with_replacement([1, 2], 2)))  
print()  
    
print ("All the combination of container in sorted order(with replacement) is:")  
print(list(combinations_with_replacement(range(2), 1))) 

In [123]:
import numpy as np

L1 = []
L2 = []
L3 = []

for i in range(3):
    value = int(input())
    if value>=1 and value <= 100:
        L1.append(int(input()))
    else:
        print("invalid value")
    
    
    
for i in range(3):
    value = int(input())
    if value>=1 and value <= 100:
        L2.append(value)
    else:
        print("invalid value")
    

for i in range(3):
    value = int(input())
    if value>=1 and value <= 100:
        L3.append(int(input()))
    else:
        print("invalid value")
        

A1 = np.array(L1)
A2 = np.array(L2)
A3 = np.array(L3)


5
4
5
3
4
5
5
4
4
47
7
7
7
7
7


In [124]:
def weight(w):
    if w in range(7001):
        if w in range(1,2001):
            print("Time Estimated: 25 minutes")
        elif w in range(2001,4001):
            print("Time Estimated: 35 minutes")
        elif w in range(4001,7001):
            print("Time Estimated: 45 minutes")
        else:
            print("Time Estimated: 0 minutes")
    else:
        print("INVALID INPUT")
        
weight(2000)

Time Estimated: 25 minutes


In [125]:
weight(0)

Time Estimated: 0 minutes


In [126]:
weight(7001)

INVALID INPUT


In [ ]:


input_text = input()

offset = int(input())

output_text = str()

def replacement(string,offset):
    refstr = 'abcdefghijklmnopqrstuvwxyz'
    case = string.islower()
    string = string.lower()
    n = refstr.find(string)
    if n==-1:
        return string
    n_offset = n + offset
    if n_offset > 25:
        n_offset = n_offset - 26
    if case:
        return refstr[n_offset]
    else:
        return refstr.upper()[n_offset]

for i in input_text:
    output_text += replacement(i,offset)
    
print(output_text)


    

In [128]:
(list(range(3)))

[0, 1, 2]

In [134]:
def maxavg(l1,l2,l3):
    avg1 = sum(l1)/3
    avg2 = sum(l2)/3
    avg3 = sum(l3)/3
    maxavg = max([avg1,avg2,avg3])
    avgvalue = [avg1,avg2,avg3]
    result = []
    for i in range(3):
        if avgvalue[i] == maxavg:
            result.append((i+1,avgvalue[i]))
    return result

l1 = []
l2 = []
l3 = []

for i in range(9):
    if i % 3 == 0:
        l1.append(int(input()))
    elif i % 3 == 1:
        l2.append(int(input()))
    else:
        l3.append(int(input()))
maxavg(l1,l2,l3)

95
92
95
90
90
90
92
90
92


[(1, 92.33333333333333), (3, 92.33333333333333)]

In [139]:
def cipher(word,key):
    result = str()
    for i in word:
        if 64 < ord(i) < 91:
            if ord(i) + key > 90:
                result += chr(ord(i) + key - 26)
            else:
                result += chr(ord(i) + key)
        elif 96 < ord(i) < 123:
            if ord(i) + key > 122:
                result += chr(ord(i) + key - 26)
            else:
                result += chr(ord(i) + key)
        elif 47 < ord(i) < 58:
            if ord(i) + key > 57:
                result += chr(ord(i) + key - 10)
            else:
                result += chr(ord(i) + key)
        else:
            result += i
    return result


cipher('abcdefghijklmnopqrstuvwxyzRONITRAJSAHUABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789',5)

'fghijklmnopqrstuvwxyzabcdeWTSNYWFOXFMZFGHIJKLMNOPQRSTUVWXYZABCDE5678901234'

In [141]:
cipher('All the best',1)

'Bmm uif cftu'

In [145]:
interior_wall_count = int(input("Please enter interior Wall Number:"))
exterior_wall_count = int(input("Please enter exterior Wall Number:"))

interior_wall = []
exterior_wall = []


for i in range(interior_wall_count):
    interior_wall.append(float(input()))

for i in range(exterior_wall_count):
    exterior_wall.append(float(input()))
    
    
interior_total = sum(map(lambda x: x*18,interior_wall))
exterior_total = sum(map(lambda x: x*12,exterior_wall))

print("the total price is : {}".format(interior_total+exterior_total))

Please enter interior Wall Number:6
Please enter exterior Wall Number:3
12.3
12.3
12.3
15.2
15.2
15.2
10.1
10.1
10.1
the total price is : 1848.5999999999997


In [142]:
for i in range(0):
    print(i)

In [143]:
for i in range(1):
    print(i)

0


In [144]:
sum(list())

0

In [146]:

Path = [800, 600, 750, 900, 1400, 1200, 1100, 1500]
BusStops = ["TH", 'GA', "IC", "HA", "TE", "LU", "NI","CA"]

start = BusStops.index(input())
stop = BusStops.index(input())

if -1 in (start,stop):
    print("INVALID INPUT")

if stop < start:
    lresult = Path[start:]
    l2 = Path[:stop]
    lresult.extend(l2)
else:
    lresult =  Path[start:stop]
    
fare = sum(lresult)/200
if fare != int(fare):
    fare = int(fare)+1
print(fare)

GA
NI
25


In [ ]:
start

In [ ]:
stop

In [ ]:
https://prepinsta.com/tcs-coding-questions/

In [ ]:
n = []

for i in range(5):
    n.append(int(input()))
    
t1 = n[3]/n[1]

t2 = n[4]/n[2]

if int(t1) == t1 or int(t2) == t2:
    print(n[0]-t1-t2)
else:
    print(n[0]-t1-t2-1)

In [ ]:
enter_parent_member = input("please the parent name:")
parent_commission = 0
child_member = input("Comma separated child members").split(',')

if len(child_member)==0:
    parent_commission = 0
else:
    for i in child_member:
        parent_commission += 500

# Output

print("TOTAL MEMBERS: {}".format(len(child_member)+1))
print("COMMISSION DETAILS")
print(enter_parent_member,": ",parent_commission)

for i in child_member:
    print(i,": ",250)

In [149]:
menu_list = {'c':['Espresso Coffee','Cappuccino Coffee','Latte Coffee'],
            't':['Plain Tea',"Assam Tea",'Ginger Tea','Cardamom Tea','Masala Tea','Lemon Tea','Green Tea','Organic Darjeeling Tea'],
            's':['Hot and Sour Soup','Veg Corn Soup','Tomato Soup','Spicy Tomato Soup'],
            'b':['Hot Chocolate Drink','Badam Drink','Badam-Pista Drink']}

print("Welcome to CCD")
main_menu = input().lower()
sub_menu = input()

try:
    print('Enjoy your ',menu_list[main_menu][int(sub_menu)-1])
except:
    print("INVALID INPUT")
    

Welcome to CCD
J
6
INVALID INPUT


In [150]:

age_list = []

try:
    for i in range(20):
        m = input("Enter the age:")

        if m == '':
            break
        elif int(m) > 120 or int(m) <= 0:
            raise Exception("INVALID INPUT")
        else:
            age_list.append(int(m))
    def fee_calculator(age):
        if age < 17:
            return 200
        elif 17 <= age < 40:
            return 400
        else:
            return 300

    fee_list = list(map(fee_calculator,age_list))
    # print(list(f for f in fee_list))
    total_fees = sum(fee_list)

    print(total_fees)

except:
    print("INVALID INPUT")
#     exit()
        



Enter the age:15
Enter the age:63
Enter the age:25
Enter the age:46
Enter the age:13
Enter the age:18
Enter the age:
1800


In [152]:
list(fee_list)

[200, 300, 400, 300, 200, 400]

In [160]:
c = lambda x,y: x if x > y


SyntaxError: invalid syntax (<ipython-input-160-c7cdd08b2aeb>, line 1)

In [162]:
c = lambda x: x >= 400
list(filter(c, fee_list))

[400, 400]

In [153]:
total_fees

1800

In [15]:
n = int(input("Please enter the input: "))

if n < 0:
    print("please enter the positive number")
else:
    if n < 2:
        print("Number is not prime")
        
    else:
        for i in range(2,n):
            if n % i == 0:
                print("Number is not Prime")
                break
        else:
            print("Number is prime")

Please enter the input: 89
Number is prime


In [165]:
def primecheck(n):
    if n > 1:
        for i in range(2,n):
            if n % i == 0:
                return False
        else:
            return True
    else:
        return False

l = []
for i in range(1000):
    if primecheck(i):
        l.append(i)
print(len(l),l)

168 [2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97, 101, 103, 107, 109, 113, 127, 131, 137, 139, 149, 151, 157, 163, 167, 173, 179, 181, 191, 193, 197, 199, 211, 223, 227, 229, 233, 239, 241, 251, 257, 263, 269, 271, 277, 281, 283, 293, 307, 311, 313, 317, 331, 337, 347, 349, 353, 359, 367, 373, 379, 383, 389, 397, 401, 409, 419, 421, 431, 433, 439, 443, 449, 457, 461, 463, 467, 479, 487, 491, 499, 503, 509, 521, 523, 541, 547, 557, 563, 569, 571, 577, 587, 593, 599, 601, 607, 613, 617, 619, 631, 641, 643, 647, 653, 659, 661, 673, 677, 683, 691, 701, 709, 719, 727, 733, 739, 743, 751, 757, 761, 769, 773, 787, 797, 809, 811, 821, 823, 827, 829, 839, 853, 857, 859, 863, 877, 881, 883, 887, 907, 911, 919, 929, 937, 941, 947, 953, 967, 971, 977, 983, 991, 997]


In [168]:

def find_num(n):
    n_series = [0,0]

    for i in range(2,n):
        if i%2 == 0:
            n_series.append(n_series[(i-2)] + 7)
        else:
            n_series.append(n_series[(i-2)] + 6)

    print(n_series[n-1])


In [169]:
find_num(18)

48


In [37]:
def geo_num(n):
    n_series = [1,1]

    for i in range(2,n):
        if i%2 == 0:
            n_series.append(n_series[(i-2)] * 2)
        else:
            n_series.append(n_series[(i-2)] * 3)

    print(n_series[-1])

In [38]:
geo_num(16)

2187


In [170]:

def find_num3(n):
    n_series = [0,0]

    for i in range(2,n):
        if i%2 == 0:
            n_series.append(n_series[(i-2)] + 2)
        else:
            n_series.append(n_series[(i-2)] + 1)

    print(n_series[-1])

In [172]:
find_num3(13)

12


In [50]:
wordlist = []

for i in range(3):
    wordlist.append(input())

vowel = ['a','e','i','o','u','A','E','I','O','U']
result1 = str()
result2 = str()

for i in wordlist[0]:
    if i in vowel:
        result1 += '%'
    else:
        result1 += i
wordlist[0] = result1

for j in wordlist[1]:
    if j in vowel:
        result2 += j
    else:
        result2 += '#'

wordlist[0] = result1
wordlist[1] = result2
        
wordlist[2] = wordlist[2].upper()

print(''.join(wordlist))

Ronir
RaJA
Sahu
R%n%r#a#ASAHU


In [56]:

def final_position(n):
    initial_position = [0,0]

    for i in range(1, n+1):
        if i%5 == 1:
            initial_position[0] += 10 * i
        elif i%5 == 2:
            initial_position[1] += 10 * i
        elif i%5 == 3:
            initial_position[0] -= 10 * i
        elif i%5 == 4:
            initial_position[1] -= 10 * i
        else:
            initial_position[0] += 10 * i
            
    print(initial_position)

In [57]:
final_position(5)

[30, -20]


In [59]:
final_position(6)

[90, -20]


In [67]:
d = {'1':1,'2':2,'3':3,'4':4,'5':5,'6':6,'7':7,'8':8,'9':9,'A':10,'B':11,'C':12,'D':13,'E':14,'F':15,'G':16,'0':0}

n = input('Please Enter the number').upper()

decimal_value = 0
j = 0
for i in n[::-1]:
    decimal_value += d[i]*(17**j)
    print(i,d[i]*(17**j))
    j += 1
    
print(decimal_value)

Please Enter the number1A
A 10
1 17
27


In [175]:
print(chr(48),chr(65),chr(97))

0 A a


In [123]:
num = input()
print(int(num,16))

1A
26


In [71]:
number = input('Please enter the number: ')
a = int()
b = int()
j = 1
for i in number:
    if j%2 == 1:
        a += int(i)
    else:
        b += int(i)
    j += 1

print(abs(a-b))

Please enter the number: 4567
2


In [74]:
key_list = ['break', 'case', 'continue', 'default', 'defer', 'else', 'for', 'func', 'goto', 'if', 'map', 'range', 'return', 'struct', 'type', 'var']

word = input("Enter the word: ")

if word in key_list:
    print('The word is present in key words')
else:
    print('The word is not present in the keywords')

Enter the word: default
The word is present in key words


In [91]:
def next_prime(n):
    k = n + 1
    while prime_check(k)==False:
        k += 1
    return(k)
    
def prime_check(k):
    if k == 2:
        return(True)
    else:
        for m in range(2,k):
            if k%m == 0:
                return False
        else:
            return True

In [78]:
True!=True

False

In [88]:
prime_check(30)

False

In [101]:
next_prime(21)

23

In [104]:
def series_out(n):
    ls = [1, 2, 1]

    for i in range(3,n):
        if i % 2 == 0:
            ls.append(ls[i-2] + ls[i-4])
        else:
            ls.append(next_prime(ls[i-2]))
    return(ls[-1])

In [105]:
series_out(14)

17

In [120]:
def prime_all(n):
    prime_list = []
    if n < 2:
        print("No Prime")
    elif n == 2:
        prime_list.append(2)
    else:
        prime_list.append(2)
        for i in range(3,n+1,2):
            for j in prime_list:
                if i % j == 0:
                    break
            else:
                prime_list.append(i)
    return prime_list,len(prime_list)

In [121]:
prime_all(101)

([2,
  3,
  5,
  7,
  11,
  13,
  17,
  19,
  23,
  29,
  31,
  37,
  41,
  43,
  47,
  53,
  59,
  61,
  67,
  71,
  73,
  79,
  83,
  89,
  97,
  101],
 26)

In [113]:
def prime(n):
    if n > 1:

        for i in range(2, n):

            if (n % i) == 0:

                print(n, "is not a prime number")

                break

        else:

            print(n, 'is a prime number')

num = int(input())

if (num > 0):

    prime(num)

else:

    print('plese')

2
2 is a prime number


In [118]:
for i in range(2,2):
    print('ronit')
else:
    print('bye ronit')
print('hi')

bye ronit
hi


In [124]:
def diffsum(n,m):
    divisible_list = []
    non_divisible_list = []
    for i in range(1,m+1):
        if i%n == 0:
            divisible_list.append(i)
        else:
            non_divisible_list.append(i)
    
    result = sum(non_divisible_list) - sum(divisible_list)
    
    return result

In [125]:
diffsum(4,20)

90

In [135]:
arr = list(map(int,input().split()))

def sorting_sum(x):
    even_list = []
    odd_list = []
    if len(x) <= 3:
        return 0
    else:
        for i in range(len(x)):
            if i % 2 == 0:
                even_list.append(x[i])
            else:
                odd_list.append(x[i])
    even_list.sort()
    odd_list.sort()
    
    return (even_list[1] + odd_list[-2]),even_list,odd_list

sorting_sum(arr)

3 2 1 7 5 4


(7, [1, 3, 5], [2, 4, 7])

In [177]:
def checksumleast(arr):
    if len(arr) < 2:
        return -1
    list_sum = sum(arr)
    min_sum2 = sum(arr[:2])
    result_arr = arr[:2]
    for i in range(len(arr)):
        for j in range(len(arr)):
            if i != j:
                sum_test = arr[i] + arr[j]
                if sum_test < min_sum2:
                    min_sum2 = sum_test
                    result_arr = [arr[i],arr[j]]
    if min_sum2 > list_sum:
        return 0
    return result_arr[0] * result_arr[1]
                

In [180]:
arr = list(map(int,input().split()))

checksumleast(arr)

4 2 43 37 01


2

In [182]:
m = str()   
for i in range(48,58):
    m += chr(i)
    
print(m)

m = str()    
for i in range(97,123):
    m += chr(i)
    
print(m)
chr(48)
# m.find('0')

0123456789
abcdefghijklmnopqrstuvwxyz


'0'

In [186]:
def change_base_from_decimal(number,base):
    n = number
    remainder = 0
    remainder_list = []
    result = ''
    while n > 0:    
        remainder_list.append(n % base)
        n //= base
    for i in remainder_list[::-1]:
        if i > 9:
            result += chr(i + 55)
        else:
            result += str(i)
    return result

In [188]:
change_base_from_decimal(5678,21)
change_base_from_decimal(718,12)

'4BA'

In [163]:
change_base_from_decimal(5678,21)

'CI8'

In [164]:
change_base_from_decimal(718,12)

'4BA'

In [189]:
int('4ba',12)

718

In [199]:
def change_base_to_decimalX(s,b):
    result = 0
    r = s[::-1]
    for i in range(len(r)):
        if ord(r[i]) > 64:
            d = ord(r[i].upper()) -64 + 9
            result += d*(b**i)
        else:
            result += int(r[i])*(b**i)
    return result
change_base_to_decimalX('CI8',21)
change_base_to_decimalX('Ci8',21)

5678

In [171]:
def movehiphenleft(s):
    r = s.replace('-','')
    hyphen_count = s.count('-')
    r = '-'*hyphen_count + r
    print(r)

In [173]:
movehiphenleft('ronit-raj-sahu-cet-tcs')

----ronitrajsahucettcs


In [31]:
def countcarry(n1,n2):
    carry_list = []
    m1 = n1
    m2 = n2
    r1 = m1 % 10
    r2 = m2 % 10
    m1 = m1 // 10
    m2 = m2 // 10
    carry_in = 0
    while m1 + m2 > 0:
        if r1 + r2 + carry_in > 9:
            carry_list.append(1)
            carry_in = 1
        else:
            carry_in = 0
            
        r1 = m1 % 10
        r2 = m2 % 10
        m1 = m1 // 10
        m2 = m2 // 10
    return(len(carry_list))
    

In [201]:
def carrycounter(m1,m2):
    n1,n2 = m1,m2
    cnt = 0
    carry = 0
    while n1 + n2 > 0:
        print(n1,n2)
        if (n1%10 + n2%10 + carry) > 9:
            cnt += 1
            carry =1
        else:
            carry = 0
        n1 = n1 // 10
        n2 = n2 // 10
        
    return cnt
# carrycounter(451,349)
# carrycounter(23,563)
carrycounter(999,1)

999 1
99 0
9 0


3

In [33]:


countcarry(451,349)

2

In [34]:
countcarry(23,563)

0

In [177]:
countcarry(999,1)

2

In [178]:
len(50)

TypeError: object of type 'int' has no len()

In [183]:
def swapchars(string, str1, str2):
    s1 = string.replace(str1,str2)
    s2 = string.replace(str2,str1)
    r = str()
    for i in range(len(string)):
        if string[i] == s1[i] and string[i] == s2[i]:
            r += string[i]
        elif string[i] != s1[i]:
            r += s1[i]
        else:
            r += s2[i]
    return r


In [205]:
def swapchars(string, str1, str2):
    return string.replace(str1,'ron##it').replace(str2,str1).replace('ron##it',str2)

In [206]:
swapchars('I am raj nitin','raj','nitin')
# 'ronit'.replace('r','u')

'I am nitin raj'

In [189]:
list(range(5,0,-1))

[5, 4, 3, 2, 1]

In [215]:
def exp_count_2(n):
    r = int()
    cnt = 0
    m = n
    while m > 0:
        if m %2 == 0:
            cnt += 1
            
        else:
            break
        m /= 2
    return cnt

In [216]:
exp_count_2(64)
l= []

In [218]:
for i in range(64,129):
    l.append(exp_count_2(i))
print(max(l))

7


In [224]:
list(map(exp_count_2,range(64,129)))

[6,
 0,
 1,
 0,
 2,
 0,
 1,
 0,
 3,
 0,
 1,
 0,
 2,
 0,
 1,
 0,
 4,
 0,
 1,
 0,
 2,
 0,
 1,
 0,
 3,
 0,
 1,
 0,
 2,
 0,
 1,
 0,
 5,
 0,
 1,
 0,
 2,
 0,
 1,
 0,
 3,
 0,
 1,
 0,
 2,
 0,
 1,
 0,
 4,
 0,
 1,
 0,
 2,
 0,
 1,
 0,
 3,
 0,
 1,
 0,
 2,
 0,
 1,
 0,
 7]

In [209]:
def exp_count_2A(n):
    r = int()
    cnt = 0
    m = n
    while m %2 == 0:
        cnt += 1
        m /= 2
#     return cnt
    if m==1:
        return cnt
    else:
        return "not an exponent"

In [210]:
exp_count_2A(48)

'not an exponent'

In [211]:
def fun_3and5(n1,n2):
    rlist = []
    if n1 < n2:
        min_n = n1
        max_n = n2
    else:
        min_n = n2
        max_n = n1
    for i in range(min_n,max_n+1):
        if i%15 == 0:
            rlist.append(i)
    return sum(rlist)


In [212]:
fun_3and5(50,12)

90

In [259]:
def sort_2nd_sum(arr):
    o_arr = []
    e_arr = []
    for i in range(len(arr)):
        if i % 2 == 0:
            e_arr.append(arr[i])
        else:
            o_arr.append(arr[i])
    o_arr.sort(reverse = True)
    e_arr.sort(reverse = True)
#     print(o_arr);print(e_arr)
    return (o_arr[1]+e_arr[1])

n = int(input())
inp_list = []
if n < 4:
    print("invalid input")
else:
    for i in range(n):
        inp_list.append(int(input()))
    p = sort_2nd_sum(inp_list)
print(p)

4
1
2
3
4
3


In [253]:
inp_list

[3, 4, 1, 7, 9]

In [260]:
def number_table(n):
    result = []
    for i in range(10):
        result.append(5*(i+1))
    return result,sum(result)

number = int(input())
l,s = number_table(number)
print(l)
print(s)

5
[5, 10, 15, 20, 25, 30, 35, 40, 45, 50]
275


In [215]:
def findpallindrome_between(n1,n2):
    order_lambda = lambda x,y: (x,y) if x < y else (y,x)
    m1,m2 = order_lambda(n1,n2)
    pallindrome = []
    for i in range(m1,m2+1):
        if str(i) == str(i)[::-1]:
            pallindrome.append(i)
    return(pallindrome,len(pallindrome))
        

In [217]:
findpallindrome_between(1,1000)

([1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9,
  11,
  22,
  33,
  44,
  55,
  66,
  77,
  88,
  99,
  101,
  111,
  121,
  131,
  141,
  151,
  161,
  171,
  181,
  191,
  202,
  212,
  222,
  232,
  242,
  252,
  262,
  272,
  282,
  292,
  303,
  313,
  323,
  333,
  343,
  353,
  363,
  373,
  383,
  393,
  404,
  414,
  424,
  434,
  444,
  454,
  464,
  474,
  484,
  494,
  505,
  515,
  525,
  535,
  545,
  555,
  565,
  575,
  585,
  595,
  606,
  616,
  626,
  636,
  646,
  656,
  666,
  676,
  686,
  696,
  707,
  717,
  727,
  737,
  747,
  757,
  767,
  777,
  787,
  797,
  808,
  818,
  828,
  838,
  848,
  858,
  868,
  878,
  888,
  898,
  909,
  919,
  929,
  939,
  949,
  959,
  969,
  979,
  989,
  999],
 108)

In [265]:
findpallindrome_between(80,10)

[11, 22, 33, 44, 55, 66, 77]

In [268]:
findpallindrome_between(80,121)

[88, 99, 101, 111, 121]

In [270]:
first_number = int(input())
second_number = int(input())

for i in range(first_number, second_number+1):
    reverse = 0
    temp = i
    while temp != 0:
        remainder = temp % 10
        reverse = (reverse * 10)+remainder
        temp = temp // 10
    if i == reverse:
        print(reverse, end=" ")

10
95
11 22 33 44 55 66 77 88 

In [218]:


copysign(x, y)

NameError: name 'copysign' is not defined

In [271]:
2**0.5

1.4142135623730951

In [278]:
x1, y1 = 1, 1
x2, y2 = 2, 4
x3, y3 = 3, 6

# p12 = ((x1-x2)**2+(y1-y2)**2)**0.5
# p23 = ((x2-x3)**2+(y2-y3)**2)**0.5
# p31 = ((x3-x1)**2+(y3-y1)**2)**0.5


p12 = round(((x1-x2)**2+(y1-y2)**2)**0.5,2)
p23 = round(((x2-x3)**2+(y2-y3)**2)**0.5,2)
p31 = round(((x3-x1)**2+(y3-y1)**2)**0.5,2)



print(p12, p23, p31)

3.16 2.24 5.39


In [274]:
import math

x1, y1 = 1, 1
x2, y2 = 2, 4
x3, y3 = 3, 6

first_diff = math.sqrt(math.pow(x2-x1, 2) + math.pow(y2-y1, 2))
second_diff = math.sqrt(math.pow(x3-x2, 2) + math.pow(y3-y2, 2))
third_diff = math.sqrt(math.pow(x3-x1, 2) + math.pow(y3-y1, 2))

print(round(first_diff,2), round(second_diff,2), round(third_diff,2))

3.16 2.24 5.39


In [1]:
def gratest_3(n1,n2,n3):
    l = [n1,n2,n3]
    l.sort()
    return(l[-1])

a = int(input())
b = int(input())
c = int(input())

gratest_3(a,b,c)
        

6
9
55


55

In [2]:
def armstrong(n):
    nstring = str(n)
    digicount = len(nstring)
    sum_of = 0
    for i in nstring:
        sum_of += int(i)**digicount
    if n == sum_of:
        print("{} is a armstrong number.".format(n))
    else:
        print("{} is not a armstrong number.".format(n))

In [3]:
armstrong(153)

153 is a armstrong number.


In [5]:
armstrong(1634)

1634 is a armstrong number.


In [8]:
year = int(input("Enter Year:"))
if year % 4 == 0:
    if year % 100 == 0:
        if year % 400 == 0:
            print("Yes, {} is Leap Year".format(year))
        else:
            print("No, {} is Leap Year".format(year))
    else:
        print("Yes, {} is Leap Year".format(year))
else:
    print("No, {} is Leap Year".format(year))

Enter Year:2008
Yes, 2008 is Leap Year


In [17]:
def primecheck(n):
    if n > 1:
        for i in range(2,n):
            if n % i == 0:
                break
        else:
            return True
        return False
    else:
        return False
            

In [40]:
primecheck(23)

True

In [42]:
prime = []
for i in range(100):
    if primecheck(i):
        prime.append(i)
print(len(prime),prime)


25 [2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97]


In [24]:

count = 0
while (count < 4):     
    count = count+1
    print(count)
    if count == 3:
        break
else:
    print("No Break") 

1
2
3


In [25]:
round(5555.4565,-5)

0.0

In [51]:
def primecheck2(n):
    if n > 1:
        for i in range(2,n):
            if n % i == 0:
                return False
        return True
    else:
        return False
            

In [55]:
prime2 = []
for i in range(50,100):
    if primecheck2(i):
        prime2.append(i)
print(len(prime2),prime2)

10 [53, 59, 61, 67, 71, 73, 79, 83, 89, 97]


In [56]:
primecheck2(2)

True

In [219]:
def sumofdigits(n):
    sumdigit = 0
    while n > 0:
        sumdigit += n % 10
        n //= 10
        print(n)
    return sumdigit

In [220]:
sumofdigits(19768)

1976
197
19
1
0


31

In [221]:
def reverse_number(n):
    rev_n = 0
    while n > 0:
        rev_n = rev_n * 10 + n % 10
        n //= 10
        print(n)
    return rev_n

reverse_number(199685)

19968
1996
199
19
1
0


586991

In [223]:
m = 1185694
n = 1185694
while m + n > 0:
    m //= 10
    n /= 10
    print(m,n)
#     break
    

118569 118569.4


In [224]:
def reverse_number2(n):
    reverse_n = int(str(n)[::-1])
    return reverse_n

In [225]:
reverse_number2(19900600)

600991

In [226]:
def palindrome(n):
    m = str(n)
    return m == m[::-1]

In [229]:
for i in range(100):
    if palindrome(i):
        print(i,end = " ")
    

0 1 2 3 4 5 6 7 8 9 11 22 33 44 55 66 77 88 99 

In [230]:
def isamstrong(n):
    m= str(n)
    digitnr = len(m)
    sr = 0
    for i in m:
        sr += int(i) ** digitnr
    return sr == n

In [231]:
isamstrong(153)

True

In [233]:
isamstrong(1634)

True

In [234]:
ams = []
for i in range(100,1000):
    if isamstrong(i):
        ams.append(i)
ams

[153, 370, 371, 407]

In [81]:
n = 20
fib = [0,1]

while len(fib) < n:
    m = fib[-1] + fib[-2]
    fib.append(m)
    
fib[n-1], fib

(4181,
 [0,
  1,
  1,
  2,
  3,
  5,
  8,
  13,
  21,
  34,
  55,
  89,
  144,
  233,
  377,
  610,
  987,
  1597,
  2584,
  4181])

In [92]:
import timeit

In [82]:
def factorial(n):
    fact  = 1
    for i in range(1,n+1):
        fact *= i
    return fact

In [95]:
timeit.timeit(lambda: "-".join(map(str, range(100))), number=10000)

0.24763944700134743

In [96]:
import time
start_time = time.time()
factorial(7)
print("--- %s seconds ---" % (time.time() - start_time))

--- 0.00012111663818359375 seconds ---


In [108]:
def factorial2(n):
    if n in (0,1):
        return 1
    else:
        return n * factorial2(n-1)

In [109]:
start_time = time.time()
print(factorial2(7))
print("--- %s seconds ---" % (time.time() - start_time))

5040
--- 0.0003077983856201172 seconds ---


In [112]:
def Isstrong_nr(n):
    m = n
    res = 0
    while m > 0:
        res += factorial2(m%10)
        m //= 10
        print(res)
    return res == n

In [113]:
Isstrong_nr(145)

120
144
145


True

In [114]:
def isperfect(n):
    proper_div = []
    for i in range(1,n):
        if n % i == 0:
            proper_div.append(i)
    return n == sum(proper_div)

In [115]:
isperfect(6)

True

In [116]:
isperfect(14)

False

In [119]:
for i in range(10000):
    if isperfect(i):
        print(i,end = ' ')

0 6 28 496 8128 

In [127]:
def isharshadnr(n):
    if n > 0:
        m = str(n)
        digicnt = 0
        for i in m:
            digicnt += int(i)
        return n % digicnt == 0

In [128]:
isharshadnr(0)

In [129]:
for i in range(1,1000):
    if isharshadnr(i):
        print(i, end = " ")

1 2 3 4 5 6 7 8 9 10 12 18 20 21 24 27 30 36 40 42 45 48 50 54 60 63 70 72 80 81 84 90 100 102 108 110 111 112 114 117 120 126 132 133 135 140 144 150 152 153 156 162 171 180 190 192 195 198 200 201 204 207 209 210 216 220 222 224 225 228 230 234 240 243 247 252 261 264 266 270 280 285 288 300 306 308 312 315 320 322 324 330 333 336 342 351 360 364 370 372 375 378 392 396 399 400 402 405 407 408 410 414 420 423 432 440 441 444 448 450 460 465 468 476 480 481 486 500 504 506 510 511 512 513 516 518 522 531 540 550 552 555 558 576 588 592 594 600 603 605 612 621 624 629 630 640 644 645 648 660 666 684 690 700 702 704 711 715 720 730 732 735 736 738 756 770 774 777 780 782 792 800 801 803 804 810 820 825 828 832 840 846 864 870 874 880 882 888 900 902 910 912 915 918 935 936 954 960 966 972 990 999 

In [194]:
def base_to_decimal(n,b):
    d = {}
    for i in range(48,58):
        d[chr(i)] = int(chr(i))
    for i in range(65,91):
        d[chr(i)] = i -64 + 9
    p = 0
    res = 0
    for i in n[::-1]:
        res += d[i]*(b**p)
        p += 1
    return res

In [195]:
n = input("Please enter the number:")

base_to_decimal(n,2)

Please enter the number:101


5

In [196]:
base_to_decimal('CI8',21)

5678

In [140]:
def decimal_2_base(n,b):
    rem_list = []
    res = ''
    while n > 0:
        rem_list.append(n % b)
        n //= b
    for i in rem_list[::-1]:
        if i < 10:
            res += str(i)
        else:
            res += chr(i + 64 -9)
    return res

In [143]:
decimal_2_base(5678,21)

'CI8'

In [39]:
def isautomorphic(n):
    m = str(n)
    ln = len(m)
    sq = n ** 2
    msq = str(sq)
    return m == msq[-ln:]

In [40]:
isautomorphic(25)

True

In [42]:
isautomorphic(70)

False

In [43]:
for i in range(1000):
    if isautomorphic(i):
        print(i, end = " ")

0 1 5 6 25 76 376 625 

In [44]:
376**2

141376

In [45]:
625**2

390625

In [46]:
print("All Automorphic Numbers between 1 and 1000.\n===========================================")
    
div = 10
    
for num in range(1,1000):
    if (div >= num):
        if((num * num) % div == num):
            print( num )
        
        elif (div <= num):
            div *= 10            
            if((num * num) % div == num):
                print( num )

All Automorphic Numbers between 1 and 1000.
1
5
6
25
76
376
625


In [237]:
for i in range(97,123):
    print(((chr(i))),end = '')
    

abcdefghijklmnopqrstuvwxyz

In [238]:
b = 'roNit'
a = b.swapcase()
a

'ROnIT'

In [239]:
def keepalpha(s):
    j = ''
    for i in s:
        if i.isalpha():
            j += i
    return j

In [240]:
keepalpha('ronitRajsahu1996_@gmail.com@2020#4')

'ronitRajsahugmailcom'

In [15]:
a = 'ronit raj sahu'

b = a.upper()

b
a

'ronit raj sahu'

In [16]:
a.title()

'Ronit Raj Sahu'

In [25]:
a = 'ronit raj sahu'

def upper_wfl(s):
    l = s.split()
    res = []
    for i in l:
        lastchr = len(i)-1
        w = ''
        for j in range(len(i)):
            if j in (0,lastchr):
                w += i[j].upper()
            else:
                w += i[j]
#             print(w)
        res.append(w)
    return ' '.join(res)

In [26]:
upper_wfl(a)

'RoniT RaJ SahU'

In [29]:
def freq_cal(a):
    st = set(a)
    d = {}
    print(st)
    for i in st:
        d[i] = a.count(i)
    return d

In [30]:
freq_cal(a)

{'n', 'j', 's', 't', ' ', 'h', 'r', 'o', 'a', 'i', 'u'}


{'n': 1,
 'j': 1,
 's': 1,
 't': 1,
 ' ': 2,
 'h': 1,
 'r': 2,
 'o': 1,
 'a': 2,
 'i': 1,
 'u': 1}

In [36]:
def pyramid1(n):
    for i in range(n+1):
        for j in range(i):
            print('*', end = ' ')
        print()
def pyramid2(n):
    for i in range(n+1):
        for j in range(2 * i - 1):
            print('*', end = ' ')
        print()
    

In [ ]:
def pyramidjust1(n):
    

In [35]:
pyramid1(5)


* 
* * 
* * * 
* * * * 
* * * * * 


In [127]:
pyramid2(5)


* 
* * * 
* * * * * 
* * * * * * * 
* * * * * * * * * 


In [54]:
def pyramid3(n):
    for i in range(n+1):
        for j in range(n-i):
            print(' ', end = ' ')
        for k in range(i):
            print('*',end = ' ')
        print()
    

In [51]:
pyramid3(29)

                                                          
                                                        * 
                                                      * * 
                                                    * * * 
                                                  * * * * 
                                                * * * * * 
                                              * * * * * * 
                                            * * * * * * * 
                                          * * * * * * * * 
                                        * * * * * * * * * 
                                      * * * * * * * * * * 
                                    * * * * * * * * * * * 
                                  * * * * * * * * * * * * 
                                * * * * * * * * * * * * * 
                              * * * * * * * * * * * * * * 
                            * * * * * * * * * * * * * * * 
                          * * * * * * * * * * * * * * * 

In [241]:
def pyramidjust3(n):
    for i in range(1,n+1):
        print(('*'*i).rjust(n))

In [242]:
pyramidjust3(5)

    *
   **
  ***
 ****
*****


In [53]:
def pyramid4(n):
    for i in range(n+1):
        for j in range(2*(n-i)):
            print(' ', end = ' ')
        for k in range(2*i-1):
            print('*',end = ' ')
        print()
    

In [58]:
pyramid4(5)

                    
                * 
            * * * 
        * * * * * 
    * * * * * * * 
* * * * * * * * * 


In [133]:
def pyramidjust4(n):
    for i in range(1,n+1):
        print(('*'*(2*i-1)).rjust(2*n-1))

In [134]:
pyramidjust4(5)

        *
      ***
    *****
  *******
*********


In [63]:
def pyramid5(n):
    for i in range(1,n+1):
        for j in range(n-i):
            print(' ', end = ' ')
        for k in range(2*i-1):
            print('*',end = ' ')
        for l in range(n-i):
            print(' ', end = ' ')
        print()

In [64]:
pyramid5(5)

        *         
      * * *       
    * * * * *     
  * * * * * * *   
* * * * * * * * * 


In [243]:
def pyramidjust5(n):
    for i in range(1,n+1):
        print(('*'*(2*i-1)).center(2*n-1))

In [244]:
pyramidjust5(5)

    *    
   ***   
  *****  
 ******* 
*********


In [245]:
def numberpyramid1(n):
    for i in range(1,n+1):
        for j in range(1,i+1):
            print(j,end = ' ')
        print()

In [246]:
numberpyramid1(5)

1 
1 2 
1 2 3 
1 2 3 4 
1 2 3 4 5 


In [85]:
def numberpyramid2(n):
    for i in range(1,n+1):
        for j in range(1,n-i+2):
            print(j,end = ' ')
        print()

In [139]:
numberpyramid2(9)

1 2 3 4 5 6 7 8 9 
1 2 3 4 5 6 7 8 
1 2 3 4 5 6 7 
1 2 3 4 5 6 
1 2 3 4 5 
1 2 3 4 
1 2 3 
1 2 
1 


In [111]:
def numberpyramid3(n):
    for i in range(1,n+1):
        for j in range(n-i):
            print('  ',end = ' ')
        for k in range(i,2*i):
            print(str(k).rjust(2,'0'),end = ' ')
        for l in range(2*(i-1),i-1,-1):
            print(str(l).rjust(2,'0'),end = ' ')
        print()
        

In [140]:
numberpyramid3(5)

            01 
         02 03 02 
      03 04 05 04 03 
   04 05 06 07 06 05 04 
05 06 07 08 09 08 07 06 05 


In [172]:
def numberpyramidjust3(n):
    for i in range(1, n+1):
        w = [str(j) for j in range(i,2*i)]
        s = ''.join(w) + ''.join(w[-1::-1][1:])
        print(s.center(2*n-1))

In [174]:
numberpyramidjust3(5)

    1    
   232   
  34543  
 4567654 
567898765


In [121]:
'ronitraj'.rfind('r')

5

In [123]:

k = 1
for i in range(1,1+9):
    for j in range(1,1+i):
        print(k,end = ' ')
        k += 1
    print()

1 
2 3 
4 5 6 
7 8 9 10 
11 12 13 14 15 
16 17 18 19 20 21 
22 23 24 25 26 27 28 
29 30 31 32 33 34 35 36 
37 38 39 40 41 42 43 44 45 


In [126]:
l = [1,2,3,4,5,5,8,9,4]

m = l.reverse()

m = reverse(l)

m

NameError: name 'reverse' is not defined

In [152]:
w = ['5', '6', '7', '8', '9']

In [171]:
w[:-4:-1]

['9', '8', '7']

In [5]:
def lcm(*argv):
    maxargv = max(argv)
    foundin = 0
    while foundin == 0:
        for i in argv:
            if maxargv % i == 0:
                pass
            else:
                break
        else:
            return maxargv
        maxargv += 1

In [6]:
lcm(5,15,27)

135

In [3]:
lcm(12,5,18)

180

In [4]:
lcm(4,8,12)

24

In [7]:
def lcm(**kwargv):
    maxargv = max(kwargv.values())
    foundin = 0
    while foundin == 0:
        for i in kwargv.values():
            if maxargv % i == 0:
                pass
            else:
                break
        else:
            return maxargv
        maxargv += 1

In [9]:
lcm(first = 15,second = 20)

60

In [19]:
{'r' : 1, 'b' : 2}.keys()

dict_keys(['r', 'b'])

In [2]:
def gcd(*numbers):
    minargs = min(numbers)
    while True:
        for i in numbers:
            if i % minargs != 0:
                break
        else:
            return minargs
        minargs -= 1
gcd(60,45,180)

15

In [3]:
%run test.py ronit raj sahu

['test.py', 'ronit', 'raj', 'sahu']
<class 'list'>
